/*
 * Created on 28 ¡.¾. 2558 ( Time 11:57:04 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.nichesoft.bean.User;
import com.nichesoft.business.service.UserService;
import com.nichesoft.web.listitem.UserListItem;

/**
 * Spring MVC controller for 'User' management.
 */
@Controller
public class UserRestController {

	@Resource
	private UserService userService;
	
	@RequestMapping( value="/items/user",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<UserListItem> findAllAsListItems() {
		List<User> list = userService.findAll();
		List<UserListItem> items = new LinkedList<UserListItem>();
		for ( User user : list ) {
			items.add(new UserListItem( user ) );
		}
		return items;
	}
	
	@RequestMapping( value="/user",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<User> findAll() {
		return userService.findAll();
	}

	@RequestMapping( value="/user/{userId}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public User findOne(@PathVariable("userId") Integer userId) {
		return userService.findById(userId);
	}
	
	@RequestMapping( value="/user",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public User create(@RequestBody User user) {
		return userService.create(user);
	}

	@RequestMapping( value="/user/{userId}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public User update(@PathVariable("userId") Integer userId, @RequestBody User user) {
		return userService.update(user);
	}

	@RequestMapping( value="/user/{userId}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("userId") Integer userId) {
		userService.delete(userId);
	}
	
}
