/*
 * Created on 28 ¡.¾. 2558 ( Time 11:57:04 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
