/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.nichesoft.web.common.AbstractController;
import com.nichesoft.web.common.FormMode;
import com.nichesoft.web.common.Message;
import com.nichesoft.web.common.MessageType;

//--- Entities
import com.nichesoft.bean.Corporate;

//--- Services 
import com.nichesoft.business.service.CorporateService;


/**
 * Spring MVC controller for 'Corporate' management.
 */
@Controller
@RequestMapping("/corporate")
public class CorporateController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "corporate";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "corporate/form";
	private static final String JSP_LIST   = "corporate/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/corporate/create";
	private static final String SAVE_ACTION_UPDATE   = "/corporate/update";

	//--- Main entity service
	@Resource
    private CorporateService corporateService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public CorporateController() {
		super(CorporateController.class, MAIN_ENTITY_NAME );
		log("CorporateController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param corporate
	 */
	private void populateModel(Model model, Corporate corporate, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, corporate);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Corporate found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Corporate> list = corporateService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Corporate
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Corporate corporate = new Corporate();	
		populateModel( model, corporate, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Corporate
	 * @param model Spring MVC model
	 * @param corporateId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{corporateId}")
	public String formForUpdate(Model model, @PathVariable("corporateId") Integer corporateId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Corporate corporate = corporateService.findById(corporateId);
		populateModel( model, corporate, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param corporate  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Corporate corporate, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Corporate corporateCreated = corporateService.create(corporate); 
				model.addAttribute(MAIN_ENTITY_NAME, corporateCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, corporate.getCorporateId() );
			} else {
				populateModel( model, corporate, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "corporate.error.create", e);
			populateModel( model, corporate, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param corporate  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Corporate corporate, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Corporate corporateSaved = corporateService.update(corporate);
				model.addAttribute(MAIN_ENTITY_NAME, corporateSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, corporate.getCorporateId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, corporate, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "corporate.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, corporate, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param corporateId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{corporateId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("corporateId") Integer corporateId) {
		log("Action 'delete'" );
		try {
			corporateService.delete( corporateId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "corporate.error.delete", e);
		}
		return redirectToList();
	}

}
