/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.nichesoft.web.common.AbstractController;
import com.nichesoft.web.common.FormMode;
import com.nichesoft.web.common.Message;
import com.nichesoft.web.common.MessageType;

//--- Entities
import com.nichesoft.bean.MenuSub;
import com.nichesoft.bean.Messages;

//--- Services 
import com.nichesoft.business.service.MenuSubService;
import com.nichesoft.business.service.MessagesService;

//--- List Items 
import com.nichesoft.web.listitem.MessagesListItem;

/**
 * Spring MVC controller for 'MenuSub' management.
 */
@Controller
@RequestMapping("/menuSub")
public class MenuSubController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "menuSub";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "menuSub/form";
	private static final String JSP_LIST   = "menuSub/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/menuSub/create";
	private static final String SAVE_ACTION_UPDATE   = "/menuSub/update";

	//--- Main entity service
	@Resource
    private MenuSubService menuSubService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private MessagesService messagesService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public MenuSubController() {
		super(MenuSubController.class, MAIN_ENTITY_NAME );
		log("MenuSubController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Messages"
	 * @param model
	 */
	private void populateListOfMessagesItems(Model model) {
		List<Messages> list = messagesService.findAll();
		List<MessagesListItem> items = new LinkedList<MessagesListItem>();
		for ( Messages messages : list ) {
			items.add(new MessagesListItem( messages ) );
		}
		model.addAttribute("listOfMessagesItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param menuSub
	 */
	private void populateModel(Model model, MenuSub menuSub, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, menuSub);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfMessagesItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfMessagesItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of MenuSub found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<MenuSub> list = menuSubService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new MenuSub
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		MenuSub menuSub = new MenuSub();	
		populateModel( model, menuSub, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing MenuSub
	 * @param model Spring MVC model
	 * @param menuSubIs  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{menuSubIs}")
	public String formForUpdate(Model model, @PathVariable("menuSubIs") Integer menuSubIs ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		MenuSub menuSub = menuSubService.findById(menuSubIs);
		populateModel( model, menuSub, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param menuSub  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid MenuSub menuSub, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				MenuSub menuSubCreated = menuSubService.create(menuSub); 
				model.addAttribute(MAIN_ENTITY_NAME, menuSubCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, menuSub.getMenuSubIs() );
			} else {
				populateModel( model, menuSub, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "menuSub.error.create", e);
			populateModel( model, menuSub, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param menuSub  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid MenuSub menuSub, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				MenuSub menuSubSaved = menuSubService.update(menuSub);
				model.addAttribute(MAIN_ENTITY_NAME, menuSubSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, menuSub.getMenuSubIs());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, menuSub, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "menuSub.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, menuSub, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param menuSubIs  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{menuSubIs}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("menuSubIs") Integer menuSubIs) {
		log("Action 'delete'" );
		try {
			menuSubService.delete( menuSubIs );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "menuSub.error.delete", e);
		}
		return redirectToList();
	}

}
