/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.nichesoft.web.common.AbstractController;
import com.nichesoft.web.common.FormMode;
import com.nichesoft.web.common.Message;
import com.nichesoft.web.common.MessageType;

//--- Entities
import com.nichesoft.bean.Permission;
import com.nichesoft.bean.MenuSub;

//--- Services 
import com.nichesoft.business.service.PermissionService;
import com.nichesoft.business.service.MenuSubService;

//--- List Items 
import com.nichesoft.web.listitem.MenuSubListItem;

/**
 * Spring MVC controller for 'Permission' management.
 */
@Controller
@RequestMapping("/permission")
public class PermissionController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "permission";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "permission/form";
	private static final String JSP_LIST   = "permission/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/permission/create";
	private static final String SAVE_ACTION_UPDATE   = "/permission/update";

	//--- Main entity service
	@Resource
    private PermissionService permissionService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private MenuSubService menuSubService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public PermissionController() {
		super(PermissionController.class, MAIN_ENTITY_NAME );
		log("PermissionController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "MenuSub"
	 * @param model
	 */
	private void populateListOfMenuSubItems(Model model) {
		List<MenuSub> list = menuSubService.findAll();
		List<MenuSubListItem> items = new LinkedList<MenuSubListItem>();
		for ( MenuSub menuSub : list ) {
			items.add(new MenuSubListItem( menuSub ) );
		}
		model.addAttribute("listOfMenuSubItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param permission
	 */
	private void populateModel(Model model, Permission permission, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, permission);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfMenuSubItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfMenuSubItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Permission found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Permission> list = permissionService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Permission
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Permission permission = new Permission();	
		populateModel( model, permission, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Permission
	 * @param model Spring MVC model
	 * @param permissionId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{permissionId}")
	public String formForUpdate(Model model, @PathVariable("permissionId") Integer permissionId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Permission permission = permissionService.findById(permissionId);
		populateModel( model, permission, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param permission  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Permission permission, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Permission permissionCreated = permissionService.create(permission); 
				model.addAttribute(MAIN_ENTITY_NAME, permissionCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, permission.getPermissionId() );
			} else {
				populateModel( model, permission, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "permission.error.create", e);
			populateModel( model, permission, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param permission  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Permission permission, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Permission permissionSaved = permissionService.update(permission);
				model.addAttribute(MAIN_ENTITY_NAME, permissionSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, permission.getPermissionId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, permission, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "permission.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, permission, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param permissionId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{permissionId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("permissionId") Integer permissionId) {
		log("Action 'delete'" );
		try {
			permissionService.delete( permissionId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "permission.error.delete", e);
		}
		return redirectToList();
	}

}
