/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.nichesoft.web.common.AbstractController;
import com.nichesoft.web.common.FormMode;
import com.nichesoft.web.common.Message;
import com.nichesoft.web.common.MessageType;

//--- Entities
import com.nichesoft.bean.ProjectUser;
import com.nichesoft.bean.Project;
import com.nichesoft.bean.User;

//--- Services 
import com.nichesoft.business.service.ProjectUserService;
import com.nichesoft.business.service.ProjectService;
import com.nichesoft.business.service.UserService;

//--- List Items 
import com.nichesoft.web.listitem.ProjectListItem;
import com.nichesoft.web.listitem.UserListItem;

/**
 * Spring MVC controller for 'ProjectUser' management.
 */
@Controller
@RequestMapping("/projectUser")
public class ProjectUserController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "projectUser";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "projectUser/form";
	private static final String JSP_LIST   = "projectUser/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/projectUser/create";
	private static final String SAVE_ACTION_UPDATE   = "/projectUser/update";

	//--- Main entity service
	@Resource
    private ProjectUserService projectUserService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private ProjectService projectService; // Injected by Spring
	@Resource
    private UserService userService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public ProjectUserController() {
		super(ProjectUserController.class, MAIN_ENTITY_NAME );
		log("ProjectUserController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Project"
	 * @param model
	 */
	private void populateListOfProjectItems(Model model) {
		List<Project> list = projectService.findAll();
		List<ProjectListItem> items = new LinkedList<ProjectListItem>();
		for ( Project project : list ) {
			items.add(new ProjectListItem( project ) );
		}
		model.addAttribute("listOfProjectItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "User"
	 * @param model
	 */
	private void populateListOfUserItems(Model model) {
		List<User> list = userService.findAll();
		List<UserListItem> items = new LinkedList<UserListItem>();
		for ( User user : list ) {
			items.add(new UserListItem( user ) );
		}
		model.addAttribute("listOfUserItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param projectUser
	 */
	private void populateModel(Model model, ProjectUser projectUser, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, projectUser);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfProjectItems(model);
			populateListOfUserItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfProjectItems(model);
			populateListOfUserItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of ProjectUser found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<ProjectUser> list = projectUserService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new ProjectUser
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		ProjectUser projectUser = new ProjectUser();	
		populateModel( model, projectUser, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing ProjectUser
	 * @param model Spring MVC model
	 * @param projectUserId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{projectUserId}")
	public String formForUpdate(Model model, @PathVariable("projectUserId") Integer projectUserId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		ProjectUser projectUser = projectUserService.findById(projectUserId);
		populateModel( model, projectUser, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param projectUser  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid ProjectUser projectUser, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				ProjectUser projectUserCreated = projectUserService.create(projectUser); 
				model.addAttribute(MAIN_ENTITY_NAME, projectUserCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, projectUser.getProjectUserId() );
			} else {
				populateModel( model, projectUser, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "projectUser.error.create", e);
			populateModel( model, projectUser, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param projectUser  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid ProjectUser projectUser, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				ProjectUser projectUserSaved = projectUserService.update(projectUser);
				model.addAttribute(MAIN_ENTITY_NAME, projectUserSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, projectUser.getProjectUserId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, projectUser, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "projectUser.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, projectUser, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param projectUserId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{projectUserId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("projectUserId") Integer projectUserId) {
		log("Action 'delete'" );
		try {
			projectUserService.delete( projectUserId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "projectUser.error.delete", e);
		}
		return redirectToList();
	}

}
