/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.nichesoft.web.common.AbstractController;
import com.nichesoft.web.common.FormMode;
import com.nichesoft.web.common.Message;
import com.nichesoft.web.common.MessageType;

//--- Entities
import com.nichesoft.bean.UserPermission;
import com.nichesoft.bean.Permission;
import com.nichesoft.bean.User;

//--- Services 
import com.nichesoft.business.service.UserPermissionService;
import com.nichesoft.business.service.PermissionService;
import com.nichesoft.business.service.UserService;

//--- List Items 
import com.nichesoft.web.listitem.PermissionListItem;
import com.nichesoft.web.listitem.UserListItem;

/**
 * Spring MVC controller for 'UserPermission' management.
 */
@Controller
@RequestMapping("/userPermission")
public class UserPermissionController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "userPermission";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "userPermission/form";
	private static final String JSP_LIST   = "userPermission/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/userPermission/create";
	private static final String SAVE_ACTION_UPDATE   = "/userPermission/update";

	//--- Main entity service
	@Resource
    private UserPermissionService userPermissionService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private PermissionService permissionService; // Injected by Spring
	@Resource
    private UserService userService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public UserPermissionController() {
		super(UserPermissionController.class, MAIN_ENTITY_NAME );
		log("UserPermissionController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Permission"
	 * @param model
	 */
	private void populateListOfPermissionItems(Model model) {
		List<Permission> list = permissionService.findAll();
		List<PermissionListItem> items = new LinkedList<PermissionListItem>();
		for ( Permission permission : list ) {
			items.add(new PermissionListItem( permission ) );
		}
		model.addAttribute("listOfPermissionItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "User"
	 * @param model
	 */
	private void populateListOfUserItems(Model model) {
		List<User> list = userService.findAll();
		List<UserListItem> items = new LinkedList<UserListItem>();
		for ( User user : list ) {
			items.add(new UserListItem( user ) );
		}
		model.addAttribute("listOfUserItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param userPermission
	 */
	private void populateModel(Model model, UserPermission userPermission, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, userPermission);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfPermissionItems(model);
			populateListOfUserItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfUserItems(model);
			populateListOfPermissionItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of UserPermission found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<UserPermission> list = userPermissionService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new UserPermission
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		UserPermission userPermission = new UserPermission();	
		populateModel( model, userPermission, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing UserPermission
	 * @param model Spring MVC model
	 * @param userPermissionId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{userPermissionId}")
	public String formForUpdate(Model model, @PathVariable("userPermissionId") Integer userPermissionId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		UserPermission userPermission = userPermissionService.findById(userPermissionId);
		populateModel( model, userPermission, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param userPermission  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid UserPermission userPermission, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				UserPermission userPermissionCreated = userPermissionService.create(userPermission); 
				model.addAttribute(MAIN_ENTITY_NAME, userPermissionCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, userPermission.getUserPermissionId() );
			} else {
				populateModel( model, userPermission, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "userPermission.error.create", e);
			populateModel( model, userPermission, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param userPermission  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid UserPermission userPermission, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				UserPermission userPermissionSaved = userPermissionService.update(userPermission);
				model.addAttribute(MAIN_ENTITY_NAME, userPermissionSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, userPermission.getUserPermissionId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, userPermission, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "userPermission.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, userPermission, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param userPermissionId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{userPermissionId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("userPermissionId") Integer userPermissionId) {
		log("Action 'delete'" );
		try {
			userPermissionService.delete( userPermissionId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "userPermission.error.delete", e);
		}
		return redirectToList();
	}

}
