/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service;

import java.util.List;

import com.nichesoft.bean.Employee;

/**
 * Business Service Interface for entity Employee.
 */
public interface EmployeeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param employeeId
	 * @return entity
	 */
	Employee findById( Integer employeeId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Employee> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Employee save(Employee entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Employee update(Employee entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Employee create(Employee entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param employeeId
	 */
	void delete( Integer employeeId );


}
