/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service;

import java.util.List;

import com.nichesoft.bean.MenuMain;

/**
 * Business Service Interface for entity MenuMain.
 */
public interface MenuMainService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param menuMainId
	 * @return entity
	 */
	MenuMain findById( Integer menuMainId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<MenuMain> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MenuMain save(MenuMain entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MenuMain update(MenuMain entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MenuMain create(MenuMain entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param menuMainId
	 */
	void delete( Integer menuMainId );


}
