/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service;

import java.util.List;

import com.nichesoft.bean.MenuSub;

/**
 * Business Service Interface for entity MenuSub.
 */
public interface MenuSubService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param menuSubIs
	 * @return entity
	 */
	MenuSub findById( Integer menuSubIs  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<MenuSub> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MenuSub save(MenuSub entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MenuSub update(MenuSub entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MenuSub create(MenuSub entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param menuSubIs
	 */
	void delete( Integer menuSubIs );


}
