/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service;

import java.util.List;

import com.nichesoft.bean.Messages;

/**
 * Business Service Interface for entity Messages.
 */
public interface MessagesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param messageId
	 * @return entity
	 */
	Messages findById( Integer messageId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Messages> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Messages save(Messages entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Messages update(Messages entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Messages create(Messages entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param messageId
	 */
	void delete( Integer messageId );


}
