/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service;

import java.util.List;

import com.nichesoft.bean.Permission;

/**
 * Business Service Interface for entity Permission.
 */
public interface PermissionService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param permissionId
	 * @return entity
	 */
	Permission findById( Integer permissionId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Permission> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Permission save(Permission entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Permission update(Permission entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Permission create(Permission entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param permissionId
	 */
	void delete( Integer permissionId );


}
