/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service;

import java.util.List;

import com.nichesoft.bean.ProjectUser;

/**
 * Business Service Interface for entity ProjectUser.
 */
public interface ProjectUserService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param projectUserId
	 * @return entity
	 */
	ProjectUser findById( Integer projectUserId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ProjectUser> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ProjectUser save(ProjectUser entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ProjectUser update(ProjectUser entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ProjectUser create(ProjectUser entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param projectUserId
	 */
	void delete( Integer projectUserId );


}
