/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service;

import java.util.List;

import com.nichesoft.bean.RolePermission;

/**
 * Business Service Interface for entity RolePermission.
 */
public interface RolePermissionService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param rolePermissionId
	 * @return entity
	 */
	RolePermission findById( Integer rolePermissionId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<RolePermission> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	RolePermission save(RolePermission entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	RolePermission update(RolePermission entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	RolePermission create(RolePermission entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param rolePermissionId
	 */
	void delete( Integer rolePermissionId );


}
