/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service;

import java.util.List;

import com.nichesoft.bean.Role;

/**
 * Business Service Interface for entity Role.
 */
public interface RoleService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param roleId
	 * @return entity
	 */
	Role findById( Integer roleId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Role> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Role save(Role entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Role update(Role entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Role create(Role entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param roleId
	 */
	void delete( Integer roleId );


}
