/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service;

import java.util.List;

import com.nichesoft.bean.UserPermission;

/**
 * Business Service Interface for entity UserPermission.
 */
public interface UserPermissionService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param userPermissionId
	 * @return entity
	 */
	UserPermission findById( Integer userPermissionId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<UserPermission> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	UserPermission save(UserPermission entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserPermission update(UserPermission entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserPermission create(UserPermission entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param userPermissionId
	 */
	void delete( Integer userPermissionId );


}
