/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.web.listitem;

import com.nichesoft.bean.Role;
import com.nichesoft.web.common.ListItem;

public class RoleListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public RoleListItem(Role role) {
		super();

		this.value = ""
			 + role.getRoleId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = role.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
