/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:18 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.nichesoft.bean.Corporate;
import com.nichesoft.bean.jpa.CorporateEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CorporateServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CorporateServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CorporateEntity' to 'Corporate'
	 * @param corporateEntity
	 */
	public Corporate mapCorporateEntityToCorporate(CorporateEntity corporateEntity) {
		if(corporateEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Corporate corporate = map(corporateEntity, Corporate.class);

		return corporate;
	}
	
	/**
	 * Mapping from 'Corporate' to 'CorporateEntity'
	 * @param corporate
	 * @param corporateEntity
	 */
	public void mapCorporateToCorporateEntity(Corporate corporate, CorporateEntity corporateEntity) {
		if(corporate == null) {
			return;
		}

		//--- Generic mapping 
		map(corporate, corporateEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}