/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.nichesoft.bean.Employee;
import com.nichesoft.bean.jpa.EmployeeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class EmployeeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public EmployeeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'EmployeeEntity' to 'Employee'
	 * @param employeeEntity
	 */
	public Employee mapEmployeeEntityToEmployee(EmployeeEntity employeeEntity) {
		if(employeeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Employee employee = map(employeeEntity, Employee.class);

		return employee;
	}
	
	/**
	 * Mapping from 'Employee' to 'EmployeeEntity'
	 * @param employee
	 * @param employeeEntity
	 */
	public void mapEmployeeToEmployeeEntity(Employee employee, EmployeeEntity employeeEntity) {
		if(employee == null) {
			return;
		}

		//--- Generic mapping 
		map(employee, employeeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}