/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.nichesoft.bean.Language;
import com.nichesoft.bean.jpa.LanguageEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class LanguageServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public LanguageServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'LanguageEntity' to 'Language'
	 * @param languageEntity
	 */
	public Language mapLanguageEntityToLanguage(LanguageEntity languageEntity) {
		if(languageEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Language language = map(languageEntity, Language.class);

		return language;
	}
	
	/**
	 * Mapping from 'Language' to 'LanguageEntity'
	 * @param language
	 * @param languageEntity
	 */
	public void mapLanguageToLanguageEntity(Language language, LanguageEntity languageEntity) {
		if(language == null) {
			return;
		}

		//--- Generic mapping 
		map(language, languageEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}