/*
 * Created on 28 ¡.¾. 2558 ( Time 11:56:52 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.nichesoft.bean.User;
import com.nichesoft.bean.jpa.UserEntity;
import com.nichesoft.bean.jpa.EmployeeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UserServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UserServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'UserEntity' to 'User'
	 * @param userEntity
	 */
	public User mapUserEntityToUser(UserEntity userEntity) {
		if(userEntity == null) {
			return null;
		}

		//--- Generic mapping 
		User user = map(userEntity, User.class);

		//--- Link mapping ( link to Employee )
		if(userEntity.getEmployee() != null) {
			user.setEmployeeId(userEntity.getEmployee().getEmployeeId());
		}
		return user;
	}
	
	/**
	 * Mapping from 'User' to 'UserEntity'
	 * @param user
	 * @param userEntity
	 */
	public void mapUserToUserEntity(User user, UserEntity userEntity) {
		if(user == null) {
			return;
		}

		//--- Generic mapping 
		map(user, userEntity);

		//--- Link mapping ( link : user )
		if( hasLinkToEmployee(user) ) {
			EmployeeEntity employee1 = new EmployeeEntity();
			employee1.setEmployeeId( user.getEmployeeId() );
			userEntity.setEmployee( employee1 );
		} else {
			userEntity.setEmployee( null );
		}

	}
	
	/**
	 * Verify that Employee id is valid.
	 * @param Employee Employee
	 * @return boolean
	 */
	private boolean hasLinkToEmployee(User user) {
		if(user.getEmployeeId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}