/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Language implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer languageId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 40 )
    private String language;

    @Size( max = 40 )
    private String shortName;

    @NotNull
    @Size( min = 1, max = 256 )
    private String flagImg;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setLanguageId( Integer languageId ) {
        this.languageId = languageId ;
    }

    public Integer getLanguageId() {
        return this.languageId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setLanguage( String language ) {
        this.language = language;
    }
    public String getLanguage() {
        return this.language;
    }

    public void setShortName( String shortName ) {
        this.shortName = shortName;
    }
    public String getShortName() {
        return this.shortName;
    }

    public void setFlagImg( String flagImg ) {
        this.flagImg = flagImg;
    }
    public String getFlagImg() {
        return this.flagImg;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(languageId);
        sb.append("|");
        sb.append(language);
        sb.append("|");
        sb.append(shortName);
        sb.append("|");
        sb.append(flagImg);
        return sb.toString(); 
    } 


}
