/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Messages implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer messageId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer languageId;

    @NotNull
    @Size( min = 1, max = 40 )
    private String messageKey;

    @NotNull
    @Size( min = 1, max = 40 )
    private String message;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setMessageId( Integer messageId ) {
        this.messageId = messageId ;
    }

    public Integer getMessageId() {
        return this.messageId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setLanguageId( Integer languageId ) {
        this.languageId = languageId;
    }
    public Integer getLanguageId() {
        return this.languageId;
    }

    public void setMessageKey( String messageKey ) {
        this.messageKey = messageKey;
    }
    public String getMessageKey() {
        return this.messageKey;
    }

    public void setMessage( String message ) {
        this.message = message;
    }
    public String getMessage() {
        return this.message;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(messageId);
        sb.append("|");
        sb.append(languageId);
        sb.append("|");
        sb.append(messageKey);
        sb.append("|");
        sb.append(message);
        return sb.toString(); 
    } 


}
