/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Permission implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer permissionId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 40 )
    private String permissionName;


    private Integer menuId;

    @NotNull
    private Boolean canView;

    @NotNull
    private Boolean canEdit;

    @NotNull
    private Boolean canInsert;

    @NotNull
    private Boolean canDelete;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPermissionId( Integer permissionId ) {
        this.permissionId = permissionId ;
    }

    public Integer getPermissionId() {
        return this.permissionId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPermissionName( String permissionName ) {
        this.permissionName = permissionName;
    }
    public String getPermissionName() {
        return this.permissionName;
    }

    public void setMenuId( Integer menuId ) {
        this.menuId = menuId;
    }
    public Integer getMenuId() {
        return this.menuId;
    }

    public void setCanView( Boolean canView ) {
        this.canView = canView;
    }
    public Boolean getCanView() {
        return this.canView;
    }

    public void setCanEdit( Boolean canEdit ) {
        this.canEdit = canEdit;
    }
    public Boolean getCanEdit() {
        return this.canEdit;
    }

    public void setCanInsert( Boolean canInsert ) {
        this.canInsert = canInsert;
    }
    public Boolean getCanInsert() {
        return this.canInsert;
    }

    public void setCanDelete( Boolean canDelete ) {
        this.canDelete = canDelete;
    }
    public Boolean getCanDelete() {
        return this.canDelete;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(permissionId);
        sb.append("|");
        sb.append(permissionName);
        sb.append("|");
        sb.append(menuId);
        sb.append("|");
        sb.append(canView);
        sb.append("|");
        sb.append(canEdit);
        sb.append("|");
        sb.append(canInsert);
        sb.append("|");
        sb.append(canDelete);
        return sb.toString(); 
    } 


}
