/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nichesoft.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "employee"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="employee", catalog="papm" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EmployeeEntity.countAll", query="SELECT COUNT(x) FROM EmployeeEntity x" )
} )
public class EmployeeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="employee_id", nullable=false)
    private Integer    employeeId   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="employee_name", nullable=false, length=40)
    private String     employeeName ;

    @Column(name="corporate_id", nullable=false)
    private Integer    corporateId  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false)
    private Date       createdAt    ;

    @Column(name="created_by", nullable=false)
    private Integer    createdBy    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="employee", targetEntity=UserEntity.class)
    private List<UserEntity> listOfUser  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EmployeeEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setEmployeeId( Integer employeeId ) {
        this.employeeId = employeeId ;
    }
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : employee_name ( VARCHAR ) 
    public void setEmployeeName( String employeeName ) {
        this.employeeName = employeeName;
    }
    public String getEmployeeName() {
        return this.employeeName;
    }

    //--- DATABASE MAPPING : corporate_id ( INT ) 
    public void setCorporateId( Integer corporateId ) {
        this.corporateId = corporateId;
    }
    public Integer getCorporateId() {
        return this.corporateId;
    }

    //--- DATABASE MAPPING : created_at ( DATETIME ) 
    public void setCreatedAt( Date createdAt ) {
        this.createdAt = createdAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }

    //--- DATABASE MAPPING : created_by ( INT ) 
    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : updated_at ( DATETIME ) 
    public void setUpdatedAt( Date updatedAt ) {
        this.updatedAt = updatedAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    //--- DATABASE MAPPING : updated_by ( INT ) 
    public void setUpdatedBy( Integer updatedBy ) {
        this.updatedBy = updatedBy;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfUser( List<UserEntity> listOfUser ) {
        this.listOfUser = listOfUser;
    }
    public List<UserEntity> getListOfUser() {
        return this.listOfUser;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(employeeId);
        sb.append("]:"); 
        sb.append(employeeName);
        sb.append("|");
        sb.append(corporateId);
        sb.append("|");
        sb.append(createdAt);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(updatedAt);
        sb.append("|");
        sb.append(updatedBy);
        return sb.toString(); 
    } 

}
