/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nichesoft.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "menu_main"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="menu_main", catalog="papm" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MenuMainEntity.countAll", query="SELECT COUNT(x) FROM MenuMainEntity x" )
} )
public class MenuMainEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="menu_main_id", nullable=false)
    private Integer    menuMainId   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="label", length=250)
    private String     label        ;

    @Column(name="seq")
    private Integer    seq          ;

	// "messageId" (column "message_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="message_id", referencedColumnName="message_id")
    private MessagesEntity messages    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MenuMainEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setMenuMainId( Integer menuMainId ) {
        this.menuMainId = menuMainId ;
    }
    public Integer getMenuMainId() {
        return this.menuMainId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : label ( VARCHAR ) 
    public void setLabel( String label ) {
        this.label = label;
    }
    public String getLabel() {
        return this.label;
    }

    //--- DATABASE MAPPING : seq ( INT ) 
    public void setSeq( Integer seq ) {
        this.seq = seq;
    }
    public Integer getSeq() {
        return this.seq;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setMessages( MessagesEntity messages ) {
        this.messages = messages;
    }
    public MessagesEntity getMessages() {
        return this.messages;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(menuMainId);
        sb.append("]:"); 
        sb.append(label);
        sb.append("|");
        sb.append(seq);
        return sb.toString(); 
    } 

}
