/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nichesoft.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "menu_sub"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="menu_sub", catalog="papm" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MenuSubEntity.countAll", query="SELECT COUNT(x) FROM MenuSubEntity x" )
} )
public class MenuSubEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="menu_sub_is", nullable=false)
    private Integer    menuSubIs    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="menu_main_id")
    private Integer    menuMainId   ;

    @Column(name="label", nullable=false, length=40)
    private String     label        ;

    @Column(name="link", nullable=false, length=256)
    private String     link         ;

    @Column(name="parent_id")
    private Integer    parentId     ;

    @Column(name="seq")
    private Integer    seq          ;

    @Column(name="is_active", nullable=false)
    private Boolean    isActive     ;

	// "messageId" (column "message_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="menuSub", targetEntity=PermissionEntity.class)
    private List<PermissionEntity> listOfPermission;

    @ManyToOne
    @JoinColumn(name="message_id", referencedColumnName="message_id")
    private MessagesEntity messages    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MenuSubEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setMenuSubIs( Integer menuSubIs ) {
        this.menuSubIs = menuSubIs ;
    }
    public Integer getMenuSubIs() {
        return this.menuSubIs;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : menu_main_id ( INT ) 
    public void setMenuMainId( Integer menuMainId ) {
        this.menuMainId = menuMainId;
    }
    public Integer getMenuMainId() {
        return this.menuMainId;
    }

    //--- DATABASE MAPPING : label ( VARCHAR ) 
    public void setLabel( String label ) {
        this.label = label;
    }
    public String getLabel() {
        return this.label;
    }

    //--- DATABASE MAPPING : link ( VARCHAR ) 
    public void setLink( String link ) {
        this.link = link;
    }
    public String getLink() {
        return this.link;
    }

    //--- DATABASE MAPPING : parent_id ( INT ) 
    public void setParentId( Integer parentId ) {
        this.parentId = parentId;
    }
    public Integer getParentId() {
        return this.parentId;
    }

    //--- DATABASE MAPPING : seq ( INT ) 
    public void setSeq( Integer seq ) {
        this.seq = seq;
    }
    public Integer getSeq() {
        return this.seq;
    }

    //--- DATABASE MAPPING : is_active ( BIT ) 
    public void setIsActive( Boolean isActive ) {
        this.isActive = isActive;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfPermission( List<PermissionEntity> listOfPermission ) {
        this.listOfPermission = listOfPermission;
    }
    public List<PermissionEntity> getListOfPermission() {
        return this.listOfPermission;
    }

    public void setMessages( MessagesEntity messages ) {
        this.messages = messages;
    }
    public MessagesEntity getMessages() {
        return this.messages;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(menuSubIs);
        sb.append("]:"); 
        sb.append(menuMainId);
        sb.append("|");
        sb.append(label);
        sb.append("|");
        sb.append(link);
        sb.append("|");
        sb.append(parentId);
        sb.append("|");
        sb.append(seq);
        sb.append("|");
        sb.append(isActive);
        return sb.toString(); 
    } 

}
