/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nichesoft.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "messages"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="messages", catalog="papm" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MessagesEntity.countAll", query="SELECT COUNT(x) FROM MessagesEntity x" )
} )
public class MessagesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="message_id", nullable=false)
    private Integer    messageId    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="message_key", nullable=false, length=40)
    private String     messageKey   ;

    @Column(name="message", nullable=false, length=40)
    private String     message      ;

	// "languageId" (column "language_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="language_id", referencedColumnName="language_id")
    private LanguageEntity language    ;

    @OneToMany(mappedBy="messages", targetEntity=MenuMainEntity.class)
    private List<MenuMainEntity> listOfMenuMain;

    @OneToMany(mappedBy="messages", targetEntity=MenuSubEntity.class)
    private List<MenuSubEntity> listOfMenuSub;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MessagesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setMessageId( Integer messageId ) {
        this.messageId = messageId ;
    }
    public Integer getMessageId() {
        return this.messageId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : message_key ( VARCHAR ) 
    public void setMessageKey( String messageKey ) {
        this.messageKey = messageKey;
    }
    public String getMessageKey() {
        return this.messageKey;
    }

    //--- DATABASE MAPPING : message ( VARCHAR ) 
    public void setMessage( String message ) {
        this.message = message;
    }
    public String getMessage() {
        return this.message;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setLanguage( LanguageEntity language ) {
        this.language = language;
    }
    public LanguageEntity getLanguage() {
        return this.language;
    }

    public void setListOfMenuMain( List<MenuMainEntity> listOfMenuMain ) {
        this.listOfMenuMain = listOfMenuMain;
    }
    public List<MenuMainEntity> getListOfMenuMain() {
        return this.listOfMenuMain;
    }

    public void setListOfMenuSub( List<MenuSubEntity> listOfMenuSub ) {
        this.listOfMenuSub = listOfMenuSub;
    }
    public List<MenuSubEntity> getListOfMenuSub() {
        return this.listOfMenuSub;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(messageId);
        sb.append("]:"); 
        sb.append(messageKey);
        sb.append("|");
        sb.append(message);
        return sb.toString(); 
    } 

}
