/*
 * Created on 27 ¡.¾. 2558 ( Time 16:44:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nichesoft.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "role"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="role", catalog="papm" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="RoleEntity.countAll", query="SELECT COUNT(x) FROM RoleEntity x" )
} )
public class RoleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="role_id", nullable=false)
    private Integer    roleId       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="role_name", length=40)
    private String     roleName     ;

    @Column(name="description", length=40)
    private String     description  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="role", targetEntity=RolePermissionEntity.class)
    private List<RolePermissionEntity> listOfRolePermission;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public RoleEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRoleId( Integer roleId ) {
        this.roleId = roleId ;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : role_name ( VARCHAR ) 
    public void setRoleName( String roleName ) {
        this.roleName = roleName;
    }
    public String getRoleName() {
        return this.roleName;
    }

    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfRolePermission( List<RolePermissionEntity> listOfRolePermission ) {
        this.listOfRolePermission = listOfRolePermission;
    }
    public List<RolePermissionEntity> getListOfRolePermission() {
        return this.listOfRolePermission;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(roleId);
        sb.append("]:"); 
        sb.append(roleName);
        sb.append("|");
        sb.append(description);
        return sb.toString(); 
    } 

}
