/*
 * Created on 27 �.�. 2558 ( Time 16:44:20 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.nichesoft.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.nichesoft.bean.User;
import com.nichesoft.bean.jpa.UserEntity;

import java.util.Date;
import java.util.List;

import com.nichesoft.business.service.UserService;
import com.nichesoft.business.service.mapping.UserServiceMapper;
import com.nichesoft.data.repository.jpa.UserJpaRepository;

import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of UserService
 */
@Component
@Transactional
public class UserServiceImpl implements UserService {

	@Resource
	private UserJpaRepository userJpaRepository;

	@Resource
	private UserServiceMapper userServiceMapper;
	
	@Override
	public User findById(Integer userId) {
		UserEntity userEntity = userJpaRepository.findOne(userId);
		return userServiceMapper.mapUserEntityToUser(userEntity);
	}

	@Override
	public List<User> findAll() {
		Iterable<UserEntity> entities = userJpaRepository.findAll();
		List<User> beans = new ArrayList<User>();
		for(UserEntity userEntity : entities) {
			beans.add(userServiceMapper.mapUserEntityToUser(userEntity));
		}
		return beans;
	}

	@Override
	public User save(User user) {
		return update(user) ;
	}

	@Override
	public User create(User user) {
		UserEntity userEntity = userJpaRepository.findOne(user.getUserId());
		if( userEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		userEntity = new UserEntity();
		userServiceMapper.mapUserToUserEntity(user, userEntity);
		UserEntity userEntitySaved = userJpaRepository.save(userEntity);
		return userServiceMapper.mapUserEntityToUser(userEntitySaved);
	}

	@Override
	public User update(User user) {
		UserEntity userEntity = userJpaRepository.findOne(user.getUserId());
		userServiceMapper.mapUserToUserEntity(user, userEntity);
		UserEntity userEntitySaved = userJpaRepository.save(userEntity);
		return userServiceMapper.mapUserEntityToUser(userEntitySaved);
	}

	@Override
	public void delete(Integer userId) {
		userJpaRepository.delete(userId);
	}

	public UserJpaRepository getUserJpaRepository() {
		return userJpaRepository;
	}

	public void setUserJpaRepository(UserJpaRepository userJpaRepository) {
		this.userJpaRepository = userJpaRepository;
	}

	public UserServiceMapper getUserServiceMapper() {
		return userServiceMapper;
	}

	public void setUserServiceMapper(UserServiceMapper userServiceMapper) {
		this.userServiceMapper = userServiceMapper;
	}
	
	//========================= Custom ========================================//
	@Override
	public User findByUserNameAndPassword( String userName , String password  ) {
		UserEntity userEntity = userJpaRepository.findByUserNameAndPassword(userName, password) ;
		return userServiceMapper.mapUserEntityToUser(userEntity);
	}

	@Override
	public User findByUserNameOrPassword(String userName, String password) {
		UserEntity userEntity = userJpaRepository.findByUserNameOrPassword(userName, password) ;
		return userServiceMapper.mapUserEntityToUser(userEntity);
	}

	@Override
	public User findByCorporateId(Integer corporateId) {
		UserEntity userEntity = userJpaRepository.findByCorporateId(corporateId) ;
		return userServiceMapper.mapUserEntityToUser(userEntity);
	}

}
